interface InitialStep {
  step_number: number;
  step_name: string;
  description?: string;
  why_matters?: string;
  dependencies?: string[];
  timeline?: string;
  order_index: number;
}

interface InitialPhase {
  phase_number: number;
  phase_name: string;
  description: string;
  steps: InitialStep[];
}

export const initialRoadmapData: InitialPhase[] = [
  {
    phase_number: 1,
    phase_name: "Discovery & Research",
    description: "This phase focuses on understanding the client's business, target audience, competitors, and overall market landscape. It's crucial for laying a solid foundation for the brand strategy.",
    steps: [
      {
        step_number: 1,
        step_name: "Client Brief & Kick-off",
        description: "Gather initial information from the client, understand their vision, goals, and expectations for the brand development project.",
        why_matters: "Ensures alignment between the client and the branding team from the outset, setting clear objectives and scope.",
        dependencies: [],
        timeline: "Week 1",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Market Research",
        description: "Analyze the industry, market trends, and external factors that could impact the brand. Identify opportunities and threats.",
        why_matters: "Provides a comprehensive understanding of the market landscape, informing strategic decisions and positioning.",
        dependencies: ["Client Brief & Kick-off"],
        timeline: "Week 1-2",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Target Audience Analysis",
        description: "Define and segment the primary and secondary target audiences. Understand their demographics, psychographics, needs, pain points, and behaviors.",
        why_matters: "Crucial for creating a brand that resonates with the intended audience and drives engagement.",
        dependencies: ["Market Research"],
        timeline: "Week 2",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Competitor Analysis",
        description: "Identify direct and indirect competitors. Analyze their branding strategies, messaging, visual identity, strengths, and weaknesses.",
        why_matters: "Helps in identifying differentiation opportunities and avoiding generic branding, ensuring the new brand stands out.",
        dependencies: ["Market Research"],
        timeline: "Week 2-3",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Internal Audit & Stakeholder Interviews",
        description: "Conduct interviews with key internal stakeholders (leadership, sales, marketing, product) to understand the company's vision, mission, values, culture, and perceived brand strengths/weaknesses.",
        why_matters: "Gathers internal perspectives and ensures the brand strategy aligns with the company's core identity and future aspirations.",
        dependencies: ["Client Brief & Kick-off"],
        timeline: "Week 3",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Brand Audit (Existing Assets)",
        description: "Review and analyze all existing brand assets (logo, website, social media, marketing materials) for consistency, effectiveness, and alignment with current business goals.",
        why_matters: "Provides a baseline understanding of the brand's current state and identifies areas for improvement or retention.",
        dependencies: ["Client Brief & Kick-off"],
        timeline: "Week 3-4",
        order_index: 5,
      },
      {
        step_number: 7,
        step_name: "SWOT Analysis",
        description: "Conduct a comprehensive SWOT (Strengths, Weaknesses, Opportunities, Threats) analysis based on all gathered research to identify key strategic areas.",
        why_matters: "Synthesizes research findings into actionable insights, guiding the development of the brand strategy.",
        dependencies: ["Market Research", "Target Audience Analysis", "Competitor Analysis", "Internal Audit & Stakeholder Interviews", "Brand Audit (Existing Assets)"],
        timeline: "Week 4",
        order_index: 6,
      },
      {
        step_number: 8,
        step_name: "Key Learnings & Insights Report",
        description: "Compile all research findings, analyses, and strategic implications into a concise report for internal team review and client presentation.",
        why_matters: "Consolidates information, ensures a shared understanding, and sets the stage for the brand strategy development phase.",
        dependencies: ["SWOT Analysis"],
        timeline: "Week 4-5",
        order_index: 7,
      },
    ],
  },
  {
    phase_number: 2,
    phase_name: "Brand Strategy Development",
    description: "This phase translates the insights from the discovery phase into a cohesive brand strategy, defining the brand's core identity and positioning.",
    steps: [
      {
        step_number: 1,
        step_name: "Brand Vision, Mission & Values",
        description: "Articulate the brand's long-term aspirations (vision), its purpose (mission), and the guiding principles (values) that define its culture and behavior.",
        why_matters: "Forms the philosophical core of the brand, guiding all future decisions and communications.",
        dependencies: ["Discovery & Research Phase Complete"],
        timeline: "Week 4",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Brand Positioning Statement",
        description: "Develop a concise statement that defines how the brand is uniquely different and better than competitors in the minds of the target audience.",
        why_matters: "Provides a clear internal compass for all marketing and communication efforts, ensuring consistency.",
        dependencies: ["Target Audience Analysis", "Competitor Analysis"],
        timeline: "Week 4-5",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Brand Personality & Archetypes",
        description: "Define the human-like characteristics and emotional tone of the brand. Explore relevant brand archetypes to deepen understanding.",
        why_matters: "Helps in creating a relatable and memorable brand voice and visual style that resonates emotionally with the audience.",
        dependencies: ["Brand Vision, Mission & Values"],
        timeline: "Week 5",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Brand Messaging Framework",
        description: "Outline key messages, taglines, and communication pillars that convey the brand's value proposition, benefits, and unique selling points.",
        why_matters: "Ensures consistent and compelling communication across all touchpoints, reinforcing the brand's identity.",
        dependencies: ["Brand Positioning Statement", "Brand Personality & Archetypes"],
        timeline: "Week 5-6",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Brand Story",
        description: "Craft a compelling narrative that communicates the brand's origin, purpose, and journey, engaging the audience on an emotional level.",
        why_matters: "A powerful brand story creates deeper connections and makes the brand more memorable and authentic.",
        dependencies: ["Brand Vision, Mission & Values", "Brand Messaging Framework"],
        timeline: "Week 6",
        order_index: 4,
      },
    ],
  },
  {
    phase_number: 3,
    phase_name: "Visual Identity Design",
    description: "This phase focuses on translating the brand strategy into a distinctive and memorable visual identity.",
    steps: [
      {
        step_number: 1,
        step_name: "Mood Boards & Creative Direction",
        description: "Develop visual mood boards to explore aesthetic directions, color palettes, typography styles, and imagery that align with the brand strategy.",
        why_matters: "Establishes a shared visual language and creative direction before diving into specific design elements, ensuring alignment with client expectations.",
        dependencies: ["Brand Strategy Development Phase Complete"],
        timeline: "Week 7",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Logo Design Concepts",
        description: "Create multiple logo concepts that embody the brand's personality, values, and positioning. Present diverse options for client review.",
        why_matters: "The logo is the most recognizable element of a brand; diverse concepts ensure a strong, unique, and versatile mark is chosen.",
        dependencies: ["Mood Boards & Creative Direction"],
        timeline: "Week 7-8",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Color Palette Development",
        description: "Select a primary and secondary color palette that evokes the desired emotions and aligns with the brand's personality and industry.",
        why_matters: "Colors play a significant role in brand recognition and emotional connection; a well-chosen palette reinforces brand identity.",
        dependencies: ["Mood Boards & Creative Direction"],
        timeline: "Week 8",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Typography Selection",
        description: "Choose primary and secondary typefaces that reflect the brand's personality and ensure readability across all applications.",
        why_matters: "Typography conveys personality and professionalism; consistent use enhances brand recognition and legibility.",
        dependencies: ["Mood Boards & Creative Direction"],
        timeline: "Week 8",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Imagery & Iconography Style",
        description: "Define the style for photography, illustrations, and icons that will be used consistently across brand communications.",
        why_matters: "Visual elements beyond the logo contribute significantly to brand perception and consistency.",
        dependencies: ["Mood Boards & Creative Direction"],
        timeline: "Week 9",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Final Logo & Visual Identity Refinement",
        description: "Based on client feedback, refine the chosen logo and visual elements to their final versions.",
        why_matters: "Ensures the client is fully satisfied with the core visual assets before broader application.",
        dependencies: ["Logo Design Concepts", "Client Feedback"],
        timeline: "Week 9-10",
        order_index: 5,
      },
    ],
  },
  {
    phase_number: 4,
    phase_name: "Brand Guidelines & Assets",
    description: "This phase compiles all strategic and visual elements into a comprehensive brand guideline document and prepares essential brand assets.",
    steps: [
      {
        step_number: 1,
        step_name: "Brand Style Guide Creation",
        description: "Develop a detailed brand style guide (brand book) that outlines the brand's strategy, visual identity rules, and usage guidelines.",
        why_matters: "Ensures consistent application of the brand across all platforms and by all stakeholders, maintaining brand integrity.",
        dependencies: ["Brand Strategy Development Phase Complete", "Visual Identity Design Phase Complete"],
        timeline: "Week 10-11",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Core Brand Assets Package",
        description: "Prepare and deliver all essential brand assets, including logo files (various formats), color codes, typography files, and imagery examples.",
        why_matters: "Provides the client with all necessary files to implement the brand across different mediums immediately.",
        dependencies: ["Final Logo & Visual Identity Refinement"],
        timeline: "Week 11",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Brand Voice & Tone Guidelines",
        description: "Document specific guidelines for the brand's written and spoken communication, ensuring consistency in messaging and personality.",
        why_matters: "Crucial for maintaining a consistent brand experience through all verbal interactions and content.",
        dependencies: ["Brand Messaging Framework", "Brand Personality & Archetypes"],
        timeline: "Week 11",
        order_index: 2,
      },
    ],
  },
  {
    phase_number: 5,
    phase_name: "Application & Implementation",
    description: "This phase applies the new brand identity to various touchpoints and prepares for launch.",
    steps: [
      {
        step_number: 1,
        step_name: "Website & Digital Presence Mock-ups",
        description: "Design mock-ups for key digital touchpoints (website, social media profiles) applying the new visual identity.",
        why_matters: "Visualizes how the brand will appear in critical digital spaces, allowing for adjustments before development.",
        dependencies: ["Brand Style Guide Creation"],
        timeline: "Week 12-13",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Marketing Collateral Design",
        description: "Design essential marketing materials (business cards, letterheads, brochures, email templates) based on the new brand guidelines.",
        why_matters: "Ensures all outward-facing materials consistently reflect the new brand identity.",
        dependencies: ["Brand Style Guide Creation"],
        timeline: "Week 13-14",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Packaging Design (if applicable)",
        description: "Develop packaging concepts and designs that align with the brand's visual identity and appeal to the target audience.",
        why_matters: "Packaging is a critical brand touchpoint, influencing perception and purchasing decisions.",
        dependencies: ["Brand Style Guide Creation"],
        timeline: "Week 14-15",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Internal Communications & Training Materials",
        description: "Create materials to educate internal teams on the new brand strategy, guidelines, and how to embody the brand.",
        why_matters: "Ensures internal alignment and empowers employees to be brand ambassadors, crucial for consistent brand delivery.",
        dependencies: ["Brand Style Guide Creation", "Brand Voice & Tone Guidelines"],
        timeline: "Week 15",
        order_index: 3,
      },
    ],
  },
  {
    phase_number: 6,
    phase_name: "Launch & Rollout Planning",
    description: "This phase focuses on strategic planning for the brand launch and its subsequent rollout.",
    steps: [
      {
        step_number: 1,
        step_name: "Launch Strategy Development",
        description: "Develop a comprehensive plan for the brand launch, including key messages, channels, and timeline.",
        why_matters: "A well-orchestrated launch maximizes impact and ensures the new brand is introduced effectively to the market.",
        dependencies: ["Application & Implementation Phase Complete"],
        timeline: "Week 16",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Communication Plan for Internal & External Audiences",
        description: "Outline specific communication strategies for informing both internal stakeholders and external audiences about the new brand.",
        why_matters: "Ensures all relevant parties are aware of the brand launch and understand its significance.",
        dependencies: ["Launch Strategy Development"],
        timeline: "Week 16-17",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Media & PR Strategy (if applicable)",
        description: "Develop a public relations strategy to generate media coverage and positive buzz around the brand launch.",
        why_matters: "Leverages external media to amplify the brand's message and reach a wider audience.",
        dependencies: ["Launch Strategy Development"],
        timeline: "Week 17",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Digital Marketing Campaign Planning",
        description: "Plan digital marketing activities (social media, email, paid ads) to support the brand launch and ongoing promotion.",
        why_matters: "Drives awareness, engagement, and traffic to the new brand's digital touchpoints.",
        dependencies: ["Launch Strategy Development"],
        timeline: "Week 17-18",
        order_index: 3,
      },
    ],
  },
  {
    phase_number: 7,
    phase_name: "Post-Launch Monitoring & Optimization",
    description: "This phase focuses on tracking brand performance after launch and making necessary adjustments for continuous improvement.",
    steps: [
      {
        step_number: 1,
        step_name: "Brand Performance Metrics Definition",
        description: "Establish key performance indicators (KPIs) to measure brand awareness, perception, engagement, and other relevant metrics.",
        why_matters: "Provides a clear framework for evaluating the success of the brand launch and ongoing brand health.",
        dependencies: ["Launch & Rollout Planning Phase Complete"],
        timeline: "Week 19",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Initial Brand Audit & Feedback Collection",
        description: "Conduct an initial audit of brand implementation across various touchpoints and gather feedback from internal and external audiences.",
        why_matters: "Identifies early successes and areas for improvement, allowing for quick adjustments.",
        dependencies: ["Brand Performance Metrics Definition"],
        timeline: "Week 19-20",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Marketing Campaign Performance Review",
        description: "Analyze the performance of digital marketing campaigns launched to support the new brand, identifying what worked and what didn't.",
        why_matters: "Optimizes future marketing efforts, ensuring efficient use of resources and improved results.",
        dependencies: ["Digital Marketing Campaign Planning"],
        timeline: "Week 20",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Brand Refinement & Iteration",
        description: "Based on performance data and feedback, make necessary refinements to the brand strategy, messaging, or visual identity.",
        why_matters: "Ensures the brand remains relevant, effective, and aligned with evolving market conditions and audience needs.",
        dependencies: ["Initial Brand Audit & Feedback Collection", "Marketing Campaign Performance Review"],
        timeline: "Ongoing",
        order_index: 3,
      },
    ],
  },
  {
    phase_number: 8,
    phase_name: "Long-Term Brand Management",
    description: "This phase outlines ongoing activities to maintain, evolve, and strengthen the brand over time.",
    steps: [
      {
        step_number: 1,
        step_name: "Ongoing Brand Monitoring & Health Checks",
        description: "Regularly monitor brand perception, market trends, and competitor activities to ensure the brand remains competitive and relevant.",
        why_matters: "Proactive monitoring helps in identifying potential issues and opportunities, allowing for timely strategic adjustments.",
        dependencies: ["Post-Launch Monitoring & Optimization Phase Complete"],
        timeline: "Ongoing",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Brand Extension & Portfolio Strategy (if applicable)",
        description: "Plan for potential brand extensions, new product/service launches, and how they fit into the overall brand architecture.",
        why_matters: "Ensures new offerings align with the core brand, maintaining consistency and leveraging brand equity.",
        dependencies: ["Ongoing Brand Monitoring & Health Checks"],
        timeline: "As needed",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Brand Evolution & Refresh Planning",
        description: "Periodically assess the need for a brand refresh or evolution to keep it modern, relevant, and appealing to target audiences.",
        why_matters: "Prevents the brand from becoming outdated and ensures it continues to resonate with its audience over time.",
        dependencies: ["Ongoing Brand Monitoring & Health Checks"],
        timeline: "Every 3-5 years",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Intellectual Property Management",
        description: "Ensure proper registration and protection of brand trademarks, copyrights, and other intellectual property.",
        why_matters: "Safeguards the brand's unique assets and prevents unauthorized use, protecting its value.",
        dependencies: [],
        timeline: "Ongoing",
        order_index: 3,
      },
    ],
  },
];