import { stepGuidanceLibrary } from '@/utils/stepGuidanceData';

interface InitialStep {
  step_number: number;
  step_name: string;
  description?: string;
  why_matters?: string;
  dependencies?: string[];
  timeline?: string;
  order_index: number;
  guiding_questions?: string[];
  expected_output?: string;
}

interface InitialPhase {
  phase_number: number;
  phase_name: string;
  description: string;
  steps: InitialStep[];
}

// Helper to safely get data from the library
const getStepData = (stepName: string) => {
  const data = stepGuidanceLibrary[stepName];
  if (!data) {
    console.warn(`Missing guidance data for step: ${stepName}`);
    return {
      description: "",
      why_matters: "",
      guiding_questions: [],
      expected_output: ""
    };
  }
  return {
    description: data.description,
    why_matters: data.why_matters,
    guiding_questions: data.guiding_questions,
    expected_output: data.expected_output
  };
};

export const initialRoadmapData: InitialPhase[] = [
  {
    phase_number: 1,
    phase_name: "Discovery & Research",
    description: "Understand the market, audience, and business context to build a solid foundation.",
    steps: [
      {
        step_number: 1,
        step_name: "Define Your Project Scope & Research Objectives", // Corrected step name
        ...getStepData("Define Your Project Scope & Research Objectives"),
        dependencies: [],
        timeline: "Week 1",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Conduct Secondary Research (Desk Research)",
        ...getStepData("Conduct Secondary Research (Desk Research)"),
        dependencies: ["Define Your Project Scope & Research Objectives"],
        timeline: "Week 1-2",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Calculate Market Sizing (TAM, SAM, SOM)",
        ...getStepData("Calculate Market Sizing (TAM, SAM, SOM)"),
        dependencies: ["Conduct Secondary Research (Desk Research)"],
        timeline: "Week 2",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Conduct Primary Research - Qualitative",
        ...getStepData("Conduct Primary Research - Qualitative"),
        dependencies: ["Conduct Secondary Research (Desk Research)"],
        timeline: "Week 2-3",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Conduct Primary Research - Quantitative",
        ...getStepData("Conduct Primary Research - Quantitative"),
        dependencies: ["Conduct Primary Research - Qualitative"],
        timeline: "Week 3-4",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Conduct Existing Brand Audit",
        ...getStepData("Conduct Existing Brand Audit"),
        dependencies: ["Define Your Project Scope & Research Objectives"],
        timeline: "Week 2",
        order_index: 5,
      },
      {
        step_number: 7,
        step_name: "Conduct SWOT Analysis",
        ...getStepData("Conduct SWOT Analysis"),
        dependencies: ["Conduct Primary Research - Quantitative", "Conduct Existing Brand Audit"],
        timeline: "Week 4",
        order_index: 6,
      },
      {
        step_number: 8,
        step_name: "Synthesize Findings & Create Research Summary Report",
        ...getStepData("Synthesize Findings & Create Research Summary Report"),
        dependencies: ["Conduct SWOT Analysis"],
        timeline: "Week 5",
        order_index: 7,
      },
      {
        step_number: 9,
        step_name: "Stakeholder Alignment & Sign-off",
        ...getStepData("Stakeholder Alignment & Sign-off"),
        dependencies: ["Synthesize Findings & Create Research Summary Report"],
        timeline: "Week 5",
        order_index: 8,
      },
    ],
  },
  {
    phase_number: 2,
    phase_name: "Brand Strategy Foundation",
    description: "Define the core identity, positioning, and messaging of the brand.",
    steps: [
      {
        step_number: 1,
        step_name: "Prepare for Strategy Workshops",
        ...getStepData("Prepare for Strategy Workshops"),
        dependencies: ["Stakeholder Alignment & Sign-off"],
        timeline: "Week 6",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Define Brand Purpose, Vision & Mission",
        ...getStepData("Define Brand Purpose, Vision & Mission"),
        dependencies: ["Prepare for Strategy Workshops"],
        timeline: "Week 6",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Identify Core Values",
        ...getStepData("Identify Core Values"),
        dependencies: ["Define Brand Purpose, Vision & Mission"],
        timeline: "Week 6",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Develop Brand Personality & Archetype",
        ...getStepData("Develop Brand Personality & Archetype"),
        dependencies: ["Identify Core Values"],
        timeline: "Week 7",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Identify Key Differentiators",
        ...getStepData("Identify Key Differentiators"),
        dependencies: ["Develop Brand Personality & Archetype"],
        timeline: "Week 7",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Craft Brand Positioning Statement",
        ...getStepData("Craft Brand Positioning Statement"),
        dependencies: ["Identify Key Differentiators"],
        timeline: "Week 7",
        order_index: 5,
      },
      {
        step_number: 7,
        step_name: "Create Brand Personality & Tone of Voice Guidelines (Initial)",
        ...getStepData("Create Brand Personality & Tone of Voice Guidelines (Initial)"),
        dependencies: ["Develop Brand Personality & Archetype"],
        timeline: "Week 8",
        order_index: 6,
      },
      {
        step_number: 8,
        step_name: "Develop Preliminary Messaging Framework",
        ...getStepData("Develop Preliminary Messaging Framework"),
        dependencies: ["Craft Brand Positioning Statement"],
        timeline: "Week 8",
        order_index: 7,
      },
      {
        step_number: 9,
        step_name: "Create Brand Identity Requirements Brief",
        ...getStepData("Create Brand Identity Requirements Brief"),
        dependencies: ["Develop Preliminary Messaging Framework"],
        timeline: "Week 8",
        order_index: 8,
      },
      {
        step_number: 10,
        step_name: "Synthesize and Document Brand Strategy Framework",
        ...getStepData("Synthesize and Document Brand Strategy Framework"),
        dependencies: ["Create Brand Identity Requirements Brief"],
        timeline: "Week 9",
        order_index: 9,
      },
    ],
  },
  {
    phase_number: 3,
    phase_name: "Visual Identity",
    description: "Translate the strategy into a distinctive visual system.",
    steps: [
      {
        step_number: 1,
        step_name: "Recruit and Brief Design Partner",
        ...getStepData("Recruit and Brief Design Partner"),
        dependencies: ["Synthesize and Document Brand Strategy Framework"],
        timeline: "Week 9",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Logo Concepts & Direction Setting",
        ...getStepData("Logo Concepts & Direction Setting"),
        dependencies: ["Recruit and Brief Design Partner"],
        timeline: "Week 10-11",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Logo Refinement & Selection",
        ...getStepData("Logo Refinement & Selection"),
        dependencies: ["Logo Concepts & Direction Setting"],
        timeline: "Week 11-12",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Develop Color Palette",
        ...getStepData("Develop Color Palette"),
        dependencies: ["Logo Concepts & Direction Setting"],
        timeline: "Week 12",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Select Typography",
        ...getStepData("Select Typography"),
        dependencies: ["Logo Concepts & Direction Setting"],
        timeline: "Week 12",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Define Imagery Style & Guidelines",
        ...getStepData("Define Imagery Style & Guidelines"),
        dependencies: ["Develop Color Palette"],
        timeline: "Week 13",
        order_index: 5,
      },
      {
        step_number: 7,
        step_name: "Create Visual Identity Mockups & Applications",
        ...getStepData("Create Visual Identity Mockups & Applications"),
        dependencies: ["Define Imagery Style & Guidelines"],
        timeline: "Week 13",
        order_index: 6,
      },
      {
        step_number: 8,
        step_name: "Prepare Final Deliverables",
        ...getStepData("Prepare Final Deliverables"),
        dependencies: ["Create Visual Identity Mockups & Applications"],
        timeline: "Week 14",
        order_index: 7,
      },
      {
        step_number: 9,
        step_name: "Gather Customer Validation",
        ...getStepData("Gather Customer Validation"),
        dependencies: ["Create Visual Identity Mockups & Applications"],
        timeline: "Week 14",
        order_index: 8,
      },
      {
        step_number: 10,
        step_name: "Get Final Approval & Handoff to Phase 4",
        ...getStepData("Get Final Approval & Handoff to Phase 4"),
        dependencies: ["Prepare Final Deliverables"],
        timeline: "Week 14",
        order_index: 9,
      },
    ],
  },
  {
    phase_number: 4,
    phase_name: "Guidelines",
    description: "Document the rules for using the brand assets to ensure consistency.",
    steps: [
      {
        step_number: 1,
        step_name: "Plan Your Brand Guidelines Structure",
        ...getStepData("Plan Your Brand Guidelines Structure"),
        dependencies: ["Get Final Approval & Handoff to Phase 4"],
        timeline: "Week 15",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Gather and Organize All Brand Assets",
        ...getStepData("Gather and Organize All Brand Assets"),
        dependencies: ["Plan Your Brand Guidelines Structure"],
        timeline: "Week 15",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Design the Brand Guidelines Document",
        ...getStepData("Design the Brand Guidelines Document"),
        dependencies: ["Gather and Organize All Brand Assets"],
        timeline: "Week 15-16",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Write Clear, Actionable Guidelines",
        ...getStepData("Write Clear, Actionable Guidelines"),
        dependencies: ["Design the Brand Guidelines Document"],
        timeline: "Week 16",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Review and Refine with Stakeholders",
        ...getStepData("Review and Refine with Stakeholders"),
        dependencies: ["Write Clear, Actionable Guidelines"],
        timeline: "Week 17",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Finalize and Prepare for Distribution",
        ...getStepData("Finalize and Prepare for Distribution"),
        dependencies: ["Review and Refine with Stakeholders"],
        timeline: "Week 17",
        order_index: 5,
      },
      {
        step_number: 7,
        step_name: "Launch and Distribute Brand Guidelines",
        ...getStepData("Launch and Distribute Brand Guidelines"),
        dependencies: ["Finalize and Prepare for Distribution"],
        timeline: "Week 18",
        order_index: 6,
      },
      {
        step_number: 8,
        step_name: "Establish Governance and Approval Processes",
        ...getStepData("Establish Governance and Approval Processes"),
        dependencies: ["Launch and Distribute Brand Guidelines"],
        timeline: "Week 18",
        order_index: 7,
      },
      {
        step_number: 9,
        step_name: "Measure Adoption and Effectiveness",
        ...getStepData("Measure Adoption and Effectiveness"),
        dependencies: ["Launch and Distribute Brand Guidelines"],
        timeline: "Ongoing",
        order_index: 8,
      },
      {
        step_number: 10,
        step_name: "Maintain and Evolve Guidelines",
        ...getStepData("Maintain and Evolve Guidelines"),
        dependencies: ["Launch and Distribute Brand Guidelines"],
        timeline: "Ongoing",
        order_index: 9,
      },
    ],
  },
  {
    phase_number: 5,
    phase_name: "Marketing Collateral",
    description: "Create the necessary assets to market and sell the brand.",
    steps: [
      {
        step_number: 1,
        step_name: "Audit Existing Materials and Define Needs",
        ...getStepData("Audit Existing Materials and Define Needs"),
        dependencies: ["Get Final Approval & Handoff to Phase 4"],
        timeline: "Week 15",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Establish Collateral Production Workflow",
        ...getStepData("Establish Collateral Production Workflow"),
        dependencies: ["Audit Existing Materials and Define Needs"],
        timeline: "Week 15",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Produce Core Business Materials",
        ...getStepData("Produce Core Business Materials"),
        dependencies: ["Establish Collateral Production Workflow"],
        timeline: "Week 16",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Develop Sales Enablement Materials",
        ...getStepData("Develop Sales Enablement Materials"),
        dependencies: ["Produce Core Business Materials"],
        timeline: "Week 16-17",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Create Marketing Communications Materials",
        ...getStepData("Create Marketing Communications Materials"),
        dependencies: ["Produce Core Business Materials"],
        timeline: "Week 17-18",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Produce Advertising and Promotional Materials",
        ...getStepData("Produce Advertising and Promotional Materials"),
        dependencies: ["Create Marketing Communications Materials"],
        timeline: "Week 18-19",
        order_index: 5,
      },
      {
        step_number: 7,
        step_name: "Organize and Manage Brand Asset Library",
        ...getStepData("Organize and Manage Brand Asset Library"),
        dependencies: ["Produce Advertising and Promotional Materials"],
        timeline: "Week 19",
        order_index: 6,
      },
      {
        step_number: 8,
        step_name: "Distribute Collateral and Train Teams",
        ...getStepData("Distribute Collateral and Train Teams"),
        dependencies: ["Organize and Manage Brand Asset Library"],
        timeline: "Week 20",
        order_index: 7,
      },
      {
        step_number: 9,
        step_name: "Monitor Usage and Gather Feedback",
        ...getStepData("Monitor Usage and Gather Feedback"),
        dependencies: ["Distribute Collateral and Train Teams"],
        timeline: "Ongoing",
        order_index: 8,
      },
    ],
  },
  {
    phase_number: 6,
    phase_name: "Launch",
    description: "Execute the go-to-market strategy for the new brand.",
    steps: [
      {
        step_number: 1,
        step_name: "Create Comprehensive Launch Plan",
        ...getStepData("Create Comprehensive Launch Plan"),
        dependencies: ["Distribute Collateral and Train Teams"],
        timeline: "Week 18",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Conduct Internal Alignment and Training",
        ...getStepData("Conduct Internal Alignment and Training"),
        dependencies: ["Create Comprehensive Launch Plan"],
        timeline: "Week 19",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Prepare All External Touchpoints",
        ...getStepData("Prepare All External Touchpoints"),
        dependencies: ["Create Comprehensive Launch Plan"],
        timeline: "Week 20",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Execute Launch Sequence",
        ...getStepData("Execute Launch Sequence"),
        dependencies: ["Prepare All External Touchpoints"],
        timeline: "Week 21",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Monitor, Measure, and Optimize",
        ...getStepData("Monitor, Measure, and Optimize"),
        dependencies: ["Execute Launch Sequence"],
        timeline: "Week 21-22",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Celebrate Success and Sustain Momentum",
        ...getStepData("Celebrate Success and Sustain Momentum"),
        dependencies: ["Execute Launch Sequence"],
        timeline: "Week 22",
        order_index: 5,
      },
    ],
  },
  {
    phase_number: 7,
    phase_name: "Operations",
    description: "Manage and grow the brand over the long term.",
    steps: [
      {
        step_number: 1,
        step_name: "Establish Brand Governance Structure",
        ...getStepData("Establish Brand Governance Structure"),
        dependencies: ["Celebrate Success and Sustain Momentum"],
        timeline: "Ongoing",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Maintain and Update Brand Guidelines",
        ...getStepData("Maintain and Update Brand Guidelines"),
        dependencies: ["Establish Brand Governance Structure"],
        timeline: "Quarterly/Annually",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Manage Brand Asset Library",
        ...getStepData("Manage Brand Asset Library"),
        dependencies: ["Establish Brand Governance Structure"],
        timeline: "Ongoing",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Provide Ongoing Training and Support",
        ...getStepData("Provide Ongoing Training and Support"),
        dependencies: ["Establish Brand Governance Structure"],
        timeline: "Ongoing",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Measure Brand Performance",
        ...getStepData("Measure Brand Performance"),
        dependencies: ["Establish Brand Governance Structure"],
        timeline: "Quarterly",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Evolve Brand as Business Grows",
        ...getStepData("Evolve Brand as Business Grows"),
        dependencies: ["Measure Brand Performance"],
        timeline: "Annually",
        order_index: 5,
      },
      {
        step_number: 7,
        step_name: "Build Brand Culture",
        ...getStepData("Build Brand Culture"),
        dependencies: ["Establish Brand Governance Structure"],
        timeline: "Ongoing",
        order_index: 6,
      },
    ],
  },
  {
    phase_number: 8,
    phase_name: "Growth",
    description: "Leverage the brand to drive business expansion.",
    steps: [
      {
        step_number: 1,
        step_name: "Develop Brand-Driven Growth Strategy",
        ...getStepData("Develop Brand-Driven Growth Strategy"),
        dependencies: ["Measure Brand Performance"],
        timeline: "Annual Planning",
        order_index: 0,
      },
      {
        step_number: 2,
        step_name: "Optimize Brand Performance",
        ...getStepData("Optimize Brand Performance"),
        dependencies: ["Develop Brand-Driven Growth Strategy"],
        timeline: "Ongoing",
        order_index: 1,
      },
      {
        step_number: 3,
        step_name: "Expand Brand Reach and Presence",
        ...getStepData("Expand Brand Reach and Presence"),
        dependencies: ["Develop Brand-Driven Growth Strategy"],
        timeline: "As needed",
        order_index: 2,
      },
      {
        step_number: 4,
        step_name: "Leverage Brand for Competitive Advantage",
        ...getStepData("Leverage Brand for Competitive Advantage"),
        dependencies: ["Develop Brand-Driven Growth Strategy"],
        timeline: "Ongoing",
        order_index: 3,
      },
      {
        step_number: 5,
        step_name: "Maximize Brand Asset Value",
        ...getStepData("Maximize Brand Asset Value"),
        dependencies: ["Develop Brand-Driven Growth Strategy"],
        timeline: "Ongoing",
        order_index: 4,
      },
      {
        step_number: 6,
        step_name: "Innovate and Stay Ahead",
        ...getStepData("Innovate and Stay Ahead"),
        dependencies: ["Develop Brand-Driven Growth Strategy"],
        timeline: "Ongoing",
        order_index: 5,
      },
    ],
  },
];